wallpaper {
    monitor = DP-1
    #path = /home/kushcool/Pictures/Wallpapers/archbtw.png
    #path = /home/kushcool/Pictures/Wallpapers/sunset-3840x2160.png         
    path = /home/kushcool/Pictures/Wallpapers-arch-default/Mountain-Sunset-3840x2160.png	
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    #path = /home/kushcool/Pictures/Wallpapers/archbtw.png
    path = /home/kushcool/Pictures/Wallpapers-arch-default/Mountain-Sunset-3840x2160.png
	fit_mode = cover
}
