preload = /home/kushcool/Wallpapers/gradient-blue.png
wallpaper = ,/home/kushcool/Wallpapers/gradient-blue.png

wallpaper {
    monitor = DP-1
    path = ~/Wallpapers/darkest-hour.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Wallpapers/darkest-hour.jpg
    fit_mode = cover
}


